os:
  - osx
  - linux
language: java
jdk:
  - oraclejdk8
addons:
  apt:
    packages:
    - npm
script:
  - xray/gradlew test -p xray
  - xray/gradlew clean install -p xray
  - plugin/gradlew test -p plugin