os:
  - osx
  - linux
language: java
addons:
  apt:
    packages:
    - npm
script:
  - jdk_switcher use openjdk8
  - xray/gradlew test -p xray
  - xray/gradlew clean install -p xray
  - plugin/gradlew test -p plugin