os:
  - osx
  - linux
osx_image: xcode9.3 # 9.4 and up uses Java 10
language: java
jdk:
  - oraclejdk8
addons:
  apt:
    packages:
    - npm
jobs:
  include:
  - stage: Test Xray client
    if: branch = master
    script: xray/gradlew test -p xray
  - stage: Install Xray client
    script: xray/gradlew clean install -p xray
  - stage: Test Idea plugin
    script: plugin/gradlew test -p plugin