os:
  - osx
  - linux
osx_image: xcode9.3 # 9.4 and up uses Java 10
language: java
jdk:
  - oraclejdk8
addons:
  apt:
    packages:
    - npm
script:
  - if [[ "$TRAVIS_BRANCH" = "master" ]]; then
      xray/gradlew test -p xray;
    fi
  - xray/gradlew clean install -p xray
  - plugin/gradlew test -p plugin