image:
- Visual Studio 2017
- Ubuntu

stack: node 8, jdk 8
environment:
  APPVEYOR_YML_DISABLE_PS_LINUX: true
  nodejs_version: "8"
  matrix:
  - JAVA_HOME: C:\Program Files\Java\jdk1.8.0

test_script:
- sh: gradlew build
- cmd: gradlew.bat build

# Don't actually build.
build: off