image:
- Visual Studio 2017
- Ubuntu

stack: node 8, jdk 8
environment:
  APPVEYOR_YML_DISABLE_PS_LINUX: true
  nodejs_version: "8"
  matrix:
  CLIENTTESTS_XRAY_URL:
    secure: 0OkcNv/5VWzZj2brUuQE6s3pI40AmtThfrmg/w+PxP0=
  CLIENTTESTS_XRAY_USERNAME:
    secure: b79qvuMVVlqhdsKoJC046g==
  CLIENTTESTS_XRAY_PASSWORD:
    secure: qTZFY5+wGrRnuM9xtfywLaz+nrAuIAxsH/g4MwVCO0hk3d1iPxfaEM7omsWW3szr6u42/ZOg62/7JDoXHWana7MZu3Cmy8dLD9ki7eIFHk4=

test_script:
- sh: if [[ "$APPVEYOR_REPO_BRANCH" = "master" && -z "$APPVEYOR_PULL_REQUEST_TITLE" ]]; then
        xray/gradlew test -p xray;
      fi
- ps: if ($env:APPVEYOR_REPO_BRANCH -eq "master" -And -Not $env:APPVEYOR_PULL_REQUEST_TITLE) {
         xray\\gradlew.bat test -p xray
      }
- ps: $env:JAVA_HOME="C:\Program Files\Java\jdk1.8.0"
- xray/gradlew clean install -p xray
- plugin/gradlew test -p plugin

# Don't actually build.
build: off