image:
- Visual Studio 2017
- Ubuntu

stack: node 8
environment:
  nodejs_version: "8"
  CLIENTTESTS_XRAY_URL:
    secure: 0OkcNv/5VWzZj2brUuQE6s3pI40AmtThfrmg/w+PxP0=
  CLIENTTESTS_XRAY_USERNAME:
    secure: b79qvuMVVlqhdsKoJC046g==
  CLIENTTESTS_XRAY_PASSWORD:
    secure: qTZFY5+wGrRnuM9xtfywLaz+nrAuIAxsH/g4MwVCO0hk3d1iPxfaEM7omsWW3szr6u42/ZOg62/7JDoXHWana7MZu3Cmy8dLD9ki7eIFHk4=

test_script:
- xray/gradlew test -p xray
- xray/gradlew clean install -p xray
- plugin/gradlew test -p plugin

# Don't actually build.
build: off